/*
 * This source file was generated by the Gradle 'init' task
 */
package io.github.wzur.gradle.kind

import io.github.wzur.gradle.kind.extension.KindExtension
import io.github.wzur.gradle.kind.task.DeleteCloudProviderKindTask
import io.github.wzur.gradle.kind.task.DeleteKindTask
import io.github.wzur.gradle.kind.task.PrepareKindConfig
import io.github.wzur.gradle.kind.task.StartKindTask
import io.github.wzur.gradle.kind.util.BinaryDownloader
import io.github.wzur.gradle.kind.util.CommandRunner
import io.github.wzur.gradle.kind.util.KIND_BUILD_FOLDER
import io.github.wzur.gradle.kind.util.KIND_DEFAULT_BINARY
import io.github.wzur.gradle.kind.util.KIND_GRADLE_TASK_GROUP
import io.github.wzur.gradle.kind.util.KIND_KUBECONFIG_FILE
import org.gradle.api.Plugin
import org.gradle.api.Project
import org.gradle.api.tasks.TaskProvider

/** A Gradle plugin to create a local Kubernetes cluster using Kind. */
class KindPlugin : Plugin<Project> {
    override fun apply(project: Project) {
        val extension =
          project.extensions.create(
            KIND_GRADLE_TASK_GROUP,
            KindExtension::class.java,
          )

        // configure conventions for simple values
        extension.version.convention("")
        extension.kindBinary.convention(
          extension.version.map { version -> BinaryDownloader().resolveKindBinary(version, KIND_DEFAULT_BINARY) }
        )
        extension.clusterName.convention(project.name)
        extension.kubernetesVersion.convention("")
        extension.nodePorts.convention(emptyList())
        extension.kindConfigDirectory.convention(project.layout.buildDirectory.dir(KIND_BUILD_FOLDER))
        extension.kubeConfigFile.convention(
          project.layout.buildDirectory.file("$KIND_BUILD_FOLDER/$KIND_KUBECONFIG_FILE")
        )
        val cloudProviderKindPidFileLocation =
          project.layout.buildDirectory.file("$KIND_BUILD_FOLDER/cloud-provider-kind.pid")

        val prepareKindConfig: TaskProvider<PrepareKindConfig> =
          project.tasks.register("prepareKindConfig", PrepareKindConfig::class.java) {
              group = KIND_GRADLE_TASK_GROUP
              description = "Prepares Kind config files"

              val nodePorts = extension.nodePorts
              val cachingRegistries = extension.mirrorDockerRegistries.map { it.toMap() }
              kindConfigDirectory.convention(extension.kindConfigDirectory)
              inputs.property("nodePorts", nodePorts)
              inputs.property("cachingRegistries", cachingRegistries)

              from(project.resources.text.fromUri(kindConfigTemplate)) {
                  expand(
                    mutableMapOf(
                      "nodePorts" to nodePorts.get(),
                      "cachingRegistries" to cachingRegistries,
                    )
                  )
                  rename { kindConfigFile.get().asFile.name }
              }
              into(kindConfigFile.get().asFile.parent)
          }

        val startKind: TaskProvider<StartKindTask> =
          project.tasks.register("startKind", StartKindTask::class.java) {
              group = KIND_GRADLE_TASK_GROUP
              description = "Starts a Kind cluster, create one if it doesn't exist"

              dependsOn(prepareKindConfig)
              // Bind extension values to task properties
              kindBinary.convention(extension.kindBinary)
              clusterName.convention(extension.clusterName)
              kubernetesVersion.convention(extension.kubernetesVersion)
              kindConfigFile.convention(prepareKindConfig.flatMap { it.kindConfigFile })
              kubeConfigFile.convention(extension.kubeConfigFile)
              dockerRegistries.convention(extension.mirrorDockerRegistries)
              dockerRegistriesInput.convention(extension.mirrorDockerRegistries.map { it.toMap() })
              nodePorts.convention(extension.nodePorts.map { it })
              if (extension.cloudProviderKind.isRequested()) {
                  cloudProviderKindBinary.convention(extension.cloudProviderKind.binary)
                  cloudProviderKindPidFile.convention(cloudProviderKindPidFileLocation)
              }
              outputs.upToDateWhen { false }
          }

        val deleteKind =
          project.tasks.register("deleteKind", DeleteKindTask::class.java) {
              group = KIND_GRADLE_TASK_GROUP
              description = "Deletes a Kind cluster"

              kindBinary.convention(extension.kindBinary)
              clusterName.convention(extension.clusterName)
              kubeConfigFile.convention(extension.kubeConfigFile)
              outputs.upToDateWhen { false }
          }

        val deleteMirrorDockerRegistries =
          project.tasks.register("deleteMirrorDockerRegistries") {
              group = KIND_GRADLE_TASK_GROUP
              description = "Deletes all mirror Docker registries created for the Kind cluster"

              val cachingRegistries = extension.mirrorDockerRegistries.map { it.toMap() }
              inputs.property("cachingRegistries", cachingRegistries)

              doLast {
                  extension.mirrorDockerRegistries.forEach { registry ->
                      logger.lifecycle("Deleting Docker registry for: ${registry.name}")
                      CommandRunner(
                          listOf<String>(
                            "docker",
                            "rm",
                            "-f",
                            registry.containerName.get(),
                          )
                        )
                        .run()
                  }
              }
          }

        val deleteCloudProviderKind =
          project.tasks.register("deleteCloudProviderKind", DeleteCloudProviderKindTask::class.java) {
              group = KIND_GRADLE_TASK_GROUP
              description = "Stops the cloud-provider-kind process started by this project"

              if (extension.cloudProviderKind.isRequested()) {
                  cloudProviderKindBinary.convention(extension.cloudProviderKind.binary)
                  cloudProviderKindPidFile.convention(cloudProviderKindPidFileLocation)
              }
              outputs.upToDateWhen { false }
          }

        project.tasks
          .matching { it.name == "clean" }
          .configureEach {
              dependsOn(deleteCloudProviderKind)
          }

        val deleteKindAll =
          project.tasks.register("deleteKindAll") {
              group = KIND_GRADLE_TASK_GROUP
              description = "Deletes all resources created by the Kind plugin for this project"

              // simply delegate to other tasks
              dependsOn(deleteKind, deleteMirrorDockerRegistries, deleteCloudProviderKind)
          }

        val debugKind =
          project.tasks.register("debugKind") {
              group = KIND_GRADLE_TASK_GROUP
              description = "Displays configuration for the Kind Gradle"

              val nodePorts = extension.nodePorts
              val cachingRegistries = extension.mirrorDockerRegistries.map { it.toMap() }
              inputs.property("nodePorts", nodePorts)
              inputs.property("cachingRegistries", cachingRegistries)
              inputs.property("kindConfigDirectory", extension.kindConfigDirectory)
              inputs.property("kubeConfigFile", extension.kubeConfigFile)

              doLast {
                  val debugMessage =
                    mutableListOf<String>(
                      "Kind plugin will create Kind cluster",
                      "named '${extension.clusterName.get()}'",
                      "\nwith command: '${if (extension.version.get().isNotBlank()) KIND_DEFAULT_BINARY else extension.kindBinary.orNull ?: KIND_DEFAULT_BINARY}'",
                      "\nwith Kind configuration directory: '${extension.kindConfigDirectory.get().asFile.absolutePath}'",
                      "\nwith kubectl configuration file: '${extension.kubeConfigFile.get().asFile.absolutePath}'",
                    )

                  if (extension.kubernetesVersion.get().isNotEmpty()) {
                      debugMessage.add("\nwith Kubernetes version: '${extension.kubernetesVersion.get()}'")
                  }

                  if (extension.version.get().isNotEmpty()) {
                      debugMessage.add("\nwith Kind binary version: '${extension.version.get()}'")
                  }

                  if (nodePorts.get().isNotEmpty()) {
                      debugMessage.add("\nwith node ports:\n  ${nodePorts.get().joinToString("\n  ")}")
                  }

                  if (extension.mirrorDockerRegistries.isNotEmpty()) {
                      debugMessage.add("\nwith Docker registries:")
                      extension.mirrorDockerRegistries.forEach { registry ->
                          debugMessage.add(
                            "\n  MirrorDockerRegistry(name=${registry.name},\n    containerName=${registry.containerName.get()},\n    remoteRegistry=${registry.remoteRegistry.get()},\n    registryUrl=${registry.registryUrl.get()})"
                          )
                          if (registry.aliases.get().isNotEmpty()) {
                              debugMessage.add(
                                "\n    aliases:\n      ${registry.aliases.get().joinToString("\n      ")}"
                              )
                          }
                      }
                  }

                  println(debugMessage.joinToString(" "))
              }
          }
    }
}
