/*
 * This source file was generated by the Gradle 'init' task
 */
package io.github.wzur.gradle.kind

import io.github.wzur.gradle.kind.extension.KindExtension
import io.github.wzur.gradle.kind.task.DeleteCloudProviderKindTask
import io.github.wzur.gradle.kind.task.DeleteKindTask
import io.github.wzur.gradle.kind.task.StartKindTask
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull
import kotlin.test.assertTrue
import org.gradle.testfixtures.ProjectBuilder

/** A simple unit test for the 'org.example.greeting' plugin. */
class KindPluginTest {
    @Test
    fun `plugin registers task`() {
        // Create a test project and apply the plugin
        val project = ProjectBuilder.builder().build()
        project.plugins.apply("base")
        project.plugins.apply("io.github.wzur.gradle.kind")

        // Verify the result
        val requireTasks =
          listOf(
            "deleteKindAll",
            "debugKind",
            "debugKind",
            "deleteKind",
            "deleteMirrorDockerRegistries",
            "deleteCloudProviderKind",
            "startKind",
          )
        requireTasks.forEach { task ->
            assertNotNull(project.tasks.findByName(task), "Task $task not found")
        }
        assertTrue(
          project.tasks.named("deleteKindAll").get().taskDependencies.getDependencies(null).any {
              it.name == "deleteCloudProviderKind"
          },
          "deleteKindAll should stop the project-owned cloud-provider-kind process",
        )
        val cleanTask = project.tasks.named("clean").get()
        assertTrue(
          cleanTask.taskDependencies.getDependencies(cleanTask).any { it.name == "deleteCloudProviderKind" },
          "clean should stop cloud-provider-kind before removing its pid file",
        )

        val startKind = project.tasks.named("startKind").get()
        assertTrue(
          startKind.outputs.files.files.contains(project.layout.buildDirectory.file("kind/kubeconfig").get().asFile),
          "startKind should declare the kubeconfig as an output",
        )

        val deleteKind = project.tasks.named("deleteKind", DeleteKindTask::class.java).get()
        assertEquals("kind", deleteKind.kindBinary.get())
        assertTrue(
          deleteKind.outputs.files.files.contains(project.layout.buildDirectory.file("kind/kubeconfig").get().asFile),
          "deleteKind should declare the kubeconfig as an output",
        )
    }

    @Test
    fun `kind version is wired to start and delete tasks`() {
        val project = ProjectBuilder.builder().build()
        project.plugins.apply("io.github.wzur.gradle.kind")

        val extension = project.extensions.getByName("kind") as KindExtension
        extension.version.set("0.30.0")

        val startKind = project.tasks.named("startKind", StartKindTask::class.java).get()
        val deleteKind = project.tasks.named("deleteKind", DeleteKindTask::class.java).get()
        assertTrue(startKind.kindBinary.isPresent)
        assertTrue(deleteKind.kindBinary.isPresent)
    }

    @Test
    fun `custom kind binary overrides version convention`() {
        val project = ProjectBuilder.builder().build()
        project.plugins.apply("io.github.wzur.gradle.kind")

        val extension = project.extensions.getByName("kind") as KindExtension
        extension.version.set("0.30.0")
        extension.kindBinary.set("custom-kind")

        val startKind = project.tasks.named("startKind", StartKindTask::class.java).get()
        assertEquals("custom-kind", startKind.kindBinary.get())
    }

    @Test
    fun `cloud provider kind is opt in and supports a custom binary`() {
        val project = ProjectBuilder.builder().build()
        project.plugins.apply("io.github.wzur.gradle.kind")

        val extension = project.extensions.getByName("kind") as KindExtension
        extension.cloudProviderKind {
            version.set("0.11.1")
            binary.set("custom-cloud-provider-kind")
        }

        val startKind = project.tasks.named("startKind", StartKindTask::class.java).get()
        assertEquals(
          "custom-cloud-provider-kind",
          startKind.cloudProviderKindBinary.get(),
        )
    }

    @Test
    fun `cloud provider kind version is available to its binary convention`() {
        val project = ProjectBuilder.builder().build()
        project.plugins.apply("io.github.wzur.gradle.kind")

        val extension = project.extensions.getByName("kind") as KindExtension
        extension.cloudProviderKind {
            version.set("0.11.1")
        }

        assertEquals("0.11.1", extension.cloudProviderKind.version.get())
        assertTrue(project.tasks.named("startKind", StartKindTask::class.java).get().cloudProviderKindBinary.isPresent)
    }

    @Test
    fun `delete cloud provider kind tolerates a missing pid file`() {
        val project = ProjectBuilder.builder().build()
        val task = project.tasks.register("deleteCloudProviderKind", DeleteCloudProviderKindTask::class.java).get()
        task.cloudProviderKindPidFile.set(project.layout.buildDirectory.file("kind/cloud-provider-kind.pid"))

        task.deleteCloudProviderKind()
    }
}
