/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/9.7.0/userguide/multi_project_builds.html in the Gradle documentation.
 */

pluginManagement {
    // Include 'plugins build' to define convention plugins.
    includeBuild("build-logic")
}

rootProject.name = "gradle-kubernetes-local-deployment-plugin"
include("gradle-kind-plugin")
