import com.diffplug.spotless.kotlin.KtfmtStep

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    // Support convention plugins written in Kotlin. Convention plugins are build scripts in 'src/main' that
    // automatically become available as plugins in the main build.
    `kotlin-dsl`

    // apply spotless plugin to itself
    alias(libs.plugins.spotless)
}

repositories {
    // Use the plugin portal to apply community plugins in convention plugins.
    gradlePluginPortal()
}

dependencies {
    implementation(libs.kotlin.gradle.plugin)
    implementation(libs.spotless.gradle.plugin)
    implementation(libs.semver.gradle.plugin)
    implementation(libs.gradle.plugin.publish)
}

spotless {
    kotlinGradle {
        ktfmt().googleStyle().configure { style ->
            style.setBlockIndent(4)
            style.setContinuationIndent(2)
            style.setMaxWidth(120)
            style.setRemoveUnusedImports(true)
            style.setTrailingCommaManagementStrategy(KtfmtStep.TrailingCommaManagementStrategy.COMPLETE)
        }
        endWithNewline()
        trimTrailingWhitespace()
    }
}
