import org.gradle.plugin.compatibility.compatibility

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Gradle plugin project to get you started.
 * For more details on writing Custom Plugins, please refer to https://docs.gradle.org/9.7.0/userguide/custom_plugins.html in the Gradle documentation.
 */

plugins {
    `kotlin-dsl`
    id("buildlogic.kotlin-gradle-plugin-conventions")
}

gradlePlugin {
    val kind =
      plugins.create("kind") {
          id = "io.github.wzur.gradle.kind"
          implementationClass = "io.github.wzur.gradle.kind.KindPlugin"
          displayName = "Gradle Kind Plugin"
          description = "Creates and manages local Kind Kubernetes clusters from Gradle."
          tags = listOf("kubernetes", "kind", "integration-testing")

          compatibility {
              features {
                  configurationCache = true
              }
          }
      }
}

dependencies {
    implementation(libs.commons.compress)
}
