/*
 * This source file was generated by the Gradle 'init' task
 */
package io.github.wzur.gradle.kind

import java.io.File
import kotlin.test.AfterTest
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import org.gradle.testkit.runner.GradleRunner
import org.junit.jupiter.api.io.TempDir

/** A simple functional test for the 'io.github.wzur.gradle.kind' plugin. */
class KindPluginFunctionalTest {
    @field:TempDir lateinit var projectDir: File

    private val buildFile by lazy { projectDir.resolve("build.gradle") }
    private val buildFileKts by lazy { projectDir.resolve("build.gradle.kts") }
    private val settingsFile by lazy { projectDir.resolve("settings.gradle") }
    private val gradleProperties by lazy {
        projectDir.resolve("gradle.properties")
    }

    @AfterTest
    fun tearDown() {
        // delete created kind clusters with shell command
        val deleteKind =
          ProcessBuilder(
              "kind",
              "delete",
              "clusters",
              "test-cluster",
              "test-project-without-extension",
            )
            .redirectOutput(ProcessBuilder.Redirect.INHERIT)
            .redirectError(ProcessBuilder.Redirect.INHERIT)
            .start()
        deleteKind.waitFor()
    }

    @Test
    fun `can overwrite kind binary`() {
        // Set up the test build
        settingsFile.writeText("")
        buildFile.writeText(
          """
          plugins {
              id('io.github.wzur.gradle.kind')
          }

          kind {
              kindBinary = "echo"
          }
          """
            .trimIndent()
        )
        gradleProperties.writeText(
          """
          org.gradle.caching=true
          org.gradle.configuration-cache=true
          org.gradle.console=verbose
          org.gradle.parallel=true
          """
            .trimIndent()
        )
        // Run the build
        val runner = GradleRunner.create()
        runner.forwardOutput()
        runner.withPluginClasspath()
        runner.withArguments("debugKind")
        runner.withProjectDir(projectDir)
        val result = runner.build()

        // Verify the result
        assertTrue(result.output.contains("with command: 'echo'"))
    }

    @Test
    fun `can run task with extension`() {
        // Set up the test build
        settingsFile.writeText("")
        buildFile.writeText(
          """
          plugins {
              id('io.github.wzur.gradle.kind')
          }
          kind {
              clusterName = "test-cluster"
              kubernetesVersion = "1.36.1"
              kubeConfigFile = file("custom-kube/kubeconfig")
              mirrorDockerRegistries {
                  dockerHub()
                  register("gcr.io")
              }
          }
          """
            .trimIndent()
        )
        gradleProperties.writeText(
          """
          org.gradle.caching=true
          org.gradle.configuration-cache=true
          org.gradle.console=verbose
          org.gradle.parallel=true
          """
            .trimIndent()
        )
        // Run the build
        val runner = GradleRunner.create()
        runner.forwardOutput()
        runner.withPluginClasspath()
        runner.withArguments("startKind")
        runner.withProjectDir(projectDir)
        val startResult = runner.build()

        // Verify the result
        assertTrue(
          startResult.output.contains("create cluster --name test-cluster --wait 60s --image kindest/node:v1.36.1")
        )
        val kubeConfigFile = File("$projectDir/custom-kube/kubeconfig")
        assertTrue(kubeConfigFile.isFile)
        assertTrue(kubeConfigFile.readText().contains("test-cluster"))

        // try to remove created Kind cluster
        runner.withArguments("deleteKind")
        val deleteResult = runner.build()

        // Verify the result
        assertTrue(deleteResult.output.contains("Deleted nodes: [\"test-cluster-control-plane\"]"))
        assertTrue(kubeConfigFile.isFile)
        assertTrue(!kubeConfigFile.readText().contains("test-cluster"))

        // try to remove created Docker registries
        runner.withArguments("deleteMirrorDockerRegistries")
        val deleteMirrorRegistries = runner.build()
        val expectedDeleteMirrorRegistriesOutputs =
          listOf(
            "Deleting Docker registry for: docker.io",
            "Deleting Docker registry for: gcr.io",
          )
        expectedDeleteMirrorRegistriesOutputs.forEach { output ->
            assertTrue(deleteMirrorRegistries.output.contains(output), "Expected output not found: $output")
        }
    }

    @Test
    fun `can run task without extension`() {
        // Set up the test build
        settingsFile.writeText(
          """
          rootProject.name = "test-project-without-extension"
          """
            .trimIndent()
        )
        buildFile.writeText(
          """
          plugins {
              id('io.github.wzur.gradle.kind')
          }
          """
            .trimIndent()
        )
        gradleProperties.writeText(
          """
          org.gradle.caching=true
          org.gradle.configuration-cache=true
          org.gradle.console=verbose
          org.gradle.parallel=true
          """
            .trimIndent()
        )
        // Run the build
        val runner = GradleRunner.create()
        runner.forwardOutput()
        runner.withPluginClasspath()
        runner.withArguments("startKind")
        runner.withProjectDir(projectDir)
        val result = runner.build()

        // Verify the result
        assertTrue(result.output.contains("create cluster --name test-project-without-extension"))
    }

    @Test
    fun `debugKind prints required information`() {
        // Set up the test build
        settingsFile.writeText(
          """
          rootProject.name = "kind-debug-with-extension"
          """
            .trimIndent()
        )
        buildFileKts.writeText(
          """
          plugins {
              id("io.github.wzur.gradle.kind")
          }

          kind {
              version.set("0.30.0")
              nodePorts.set( listOf(30080, 30081) )
              mirrorDockerRegistries {
                register("gcr.io")
                dockerHub()
                register("internal:5000") {
                    registryUrl.set("https://internal")
                }
              }
          }
          """
            .trimIndent()
        )
        gradleProperties.writeText(
          """
          org.gradle.caching=true
          org.gradle.configuration-cache=true
          org.gradle.console=verbose
          org.gradle.parallel=true
          """
            .trimIndent()
        )
        // Run the build
        val runner = GradleRunner.create()
        runner.forwardOutput()
        runner.withPluginClasspath()
        runner.withArguments("debugKind")
        runner.withProjectDir(projectDir)
        val result = runner.build()

        // Verify the result
        assertTrue(
          result.output.contains(
            "Kind plugin will create Kind cluster named 'kind-debug-with-extension' \n" +
              "with command: 'kind' \n" +
              "with Kind configuration directory: '${File("$projectDir/build/kind").absolutePath}' \n" +
              "with kubectl configuration file: '${File("$projectDir/build/kind/kubeconfig").absolutePath}' \n" +
              "with Kind binary version: '0.30.0' \n" +
              "with node ports:\n" +
              "  30080\n" +
              "  30081 \n" +
              "with Docker registries: \n" +
              "  MirrorDockerRegistry(name=docker.io,\n" +
              "    containerName=docker-io,\n" +
              "    remoteRegistry=docker.io,\n" +
              "    registryUrl=https://registry-1.docker.io) \n" +
              "    aliases:\n" +
              "      registry-1.docker.io \n" +
              "  MirrorDockerRegistry(name=gcr.io,\n" +
              "    containerName=gcr-io,\n" +
              "    remoteRegistry=gcr.io,\n" +
              "    registryUrl=https://gcr.io) \n" +
              "  MirrorDockerRegistry(name=internal:5000,\n" +
              "    containerName=internal-5000,\n" +
              "    remoteRegistry=internal:5000,\n" +
              "    registryUrl=https://internal)\n"
          )
        )
    }

    @Test
    fun `can configure registry aliases with Groovy DSL`() {
        settingsFile.writeText("")
        buildFile.writeText(
          """
          plugins {
            id('io.github.wzur.gradle.kind')
          }
          kind {
            mirrorDockerRegistries {
              register('gcr.io') {
                aliases = ['gcr-1.io', 'gcr-2.io']
              }
            }
          }
          """
            .trimIndent()
        )

        val runner = GradleRunner.create()
        runner.forwardOutput()
        runner.withPluginClasspath()
        runner.withArguments("debugKind")
        runner.withProjectDir(projectDir)
        val result = runner.build()

        assertTrue(result.output.contains("aliases:\n      gcr-1.io\n      gcr-2.io"))
    }

    @Test
    fun `prepareKindConfig creates Kind config file`() {
        // Set up the test build
        settingsFile.writeText(
          """
          rootProject.name = "prepare-kind-config"
          """
            .trimIndent()
        )
        buildFile.writeText(
          """
          plugins {
              id('io.github.wzur.gradle.kind')
          }
          kind {
              nodePorts = [30080, 30081]
              mirrorDockerRegistries {
                  dockerHub()
              }
          }
          """
            .trimIndent()
        )
        gradleProperties.writeText(
          """
          org.gradle.caching=true
          org.gradle.configuration-cache=true
          org.gradle.console=verbose
          org.gradle.parallel=true
          """
            .trimIndent()
        )
        // Run the build
        val runner = GradleRunner.create()
        runner.forwardOutput()
        runner.withPluginClasspath()
        runner.withArguments("prepareKindConfig")
        runner.withProjectDir(projectDir)
        val result = runner.build()

        // read the content of the generated file
        val generatedFile = File("$projectDir/build/kind/cluster.yaml")
        val generatedFileContent = generatedFile.readText()
        // Verify the result
        assertEquals(
          KindPluginFunctionalTest::class.java.getResource("/generatedCluster.yaml")?.readText(),
          generatedFileContent,
        )
    }

    @Test
    fun `prepareKindConfig uses configured kind config directory`() {
        settingsFile.writeText("")
        buildFile.writeText(
          """
          plugins {
            id('io.github.wzur.gradle.kind')
          }
          kind {
            kindConfigDirectory = file('custom-kind')
            mirrorDockerRegistries {
              dockerHub()
            }
          }
          """
            .trimIndent()
        )

        val runner = GradleRunner.create()
        runner.forwardOutput()
        runner.withPluginClasspath()
        runner.withArguments("prepareKindConfig")
        runner.withProjectDir(projectDir)
        runner.build()

        assertTrue(File("$projectDir/custom-kind/cluster.yaml").isFile)
    }

    @Test
    fun `startKind uses configured kind config directory`() {
        settingsFile.writeText("")
        buildFile.writeText(
          """
          plugins {
              id('io.github.wzur.gradle.kind')
          }
          kind {
            kindBinary = 'echo'
            kindConfigDirectory = file('custom-kind')
            kubeConfigFile = file('custom-kube/kubeconfig')
          }
          """
            .trimIndent()
        )

        val runner = GradleRunner.create()
        runner.forwardOutput()
        runner.withPluginClasspath()
        runner.withArguments("startKind")
        runner.withProjectDir(projectDir)
        val result = runner.build()

        assertTrue(result.output.contains("--config $projectDir/custom-kind/cluster.yaml"))
        assertTrue(result.output.contains("--kubeconfig $projectDir/custom-kube/kubeconfig"))
    }
}
